# documentation at http://goreleaser.com
project_name: esplus
before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
     - "-s -w -X 'main.version={{ .Version }}'"
archives:
  - replacements:
      darwin: MacOS
      linux: Linux
      windows: Windows
      386: 32bit
      amd64: 64bit
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
